package com.sframe.component.demo.single.bean;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo_student.student_id
     *
     * @mbggenerated
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo_student.student_name
     *
     * @mbggenerated
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo_student.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo_student.student_age
     *
     * @mbggenerated
     */
    private Integer studentAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo_student.student_desc
     *
     * @mbggenerated
     */
    private String studentDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo_student.student_id
     *
     * @return the value of t_demo_student.student_id
     *
     * @mbggenerated
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo_student.student_id
     *
     * @param studentId the value for t_demo_student.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo_student.student_name
     *
     * @return the value of t_demo_student.student_name
     *
     * @mbggenerated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo_student.student_name
     *
     * @param studentName the value for t_demo_student.student_name
     *
     * @mbggenerated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo_student.real_name
     *
     * @return the value of t_demo_student.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo_student.real_name
     *
     * @param realName the value for t_demo_student.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo_student.student_age
     *
     * @return the value of t_demo_student.student_age
     *
     * @mbggenerated
     */
    public Integer getStudentAge() {
        return studentAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo_student.student_age
     *
     * @param studentAge the value for t_demo_student.student_age
     *
     * @mbggenerated
     */
    public void setStudentAge(Integer studentAge) {
        this.studentAge = studentAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo_student.student_desc
     *
     * @return the value of t_demo_student.student_desc
     *
     * @mbggenerated
     */
    public String getStudentDesc() {
        return studentDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo_student.student_desc
     *
     * @param studentDesc the value for t_demo_student.student_desc
     *
     * @mbggenerated
     */
    public void setStudentDesc(String studentDesc) {
        this.studentDesc = studentDesc == null ? null : studentDesc.trim();
    }
}