# 开发环境配置
spring:
  profiles: dev

  # tomcat 配置
  server:
      port: 8080

  # 数据库访问配置
  datasource:
      name: sframe_db
      url: jdbc:mysql://jinyutao-host1.sh2.newtouch.com:45040/sframe_db?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true
      username: sframe
      password: 123456

      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j

      # 连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000

      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000

      # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties:
          druid.stat.mergeSql: true
          druid.stat.slowSqlMillis: 5000
